/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package preguntasFrecuentes;

import GUI.GuiPrincipal;
import javax.swing.SwingUtilities;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author mynit
 */
public class PreguntasFrecuentesForm extends javax.swing.JFrame {

    private String currentUser;
    /**
     * Creates new form PreguntasFrecuentesForm
     */
    public PreguntasFrecuentesForm(String username) {
        this.currentUser = username;
        initComponents();
        setupFAQs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        flechaIzquierda1 = new javax.swing.JButton();
        searchButton1 = new javax.swing.JButton();
        recargar1 = new javax.swing.JButton();
        menuButton1 = new javax.swing.JButton();
        bookmarkButton1 = new javax.swing.JButton();
        searchField1 = new javax.swing.JTextField();
        flechaDerecha1 = new javax.swing.JButton();
        scrollbar1 = new java.awt.Scrollbar();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(178, 171, 171));

        jPanel3.setBackground(new java.awt.Color(178, 171, 171));

        flechaIzquierda1.setText("←");
        flechaIzquierda1.setToolTipText("");
        flechaIzquierda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flechaIzquierda1ActionPerformed(evt);
            }
        });

        searchButton1.setText("🔍");
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });

        recargar1.setText("🔄");

        menuButton1.setText("☰");
        menuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(evt);
            }
        });

        bookmarkButton1.setText("🔖");
        bookmarkButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookmarkButton1ActionPerformed(evt);
            }
        });

        searchField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchField1ActionPerformed(evt);
            }
        });

        flechaDerecha1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        flechaDerecha1.setText("→");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flechaIzquierda1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flechaDerecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(recargar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookmarkButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookmarkButton1)
                    .addComponent(menuButton1)
                    .addComponent(flechaIzquierda1)
                    .addComponent(searchButton1)
                    .addComponent(flechaDerecha1)
                    .addComponent(recargar1))
                .addContainerGap())
        );

        jLabel3.setText("Pregunta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addContainerGap(293, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jLabel2.setText("Pregunta");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("Productos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)))
                        .addComponent(scrollbar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollbar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 159, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void flechaIzquierda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flechaIzquierda1ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        SwingUtilities.invokeLater(() -> {
            new GuiPrincipal(currentUser).setVisible(true);
        });
    }//GEN-LAST:event_flechaIzquierda1ActionPerformed

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
        // TODO add your handling code here:
        handleSearch();
    }//GEN-LAST:event_searchButton1ActionPerformed

    private void menuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuButton1ActionPerformed

    private void bookmarkButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookmarkButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookmarkButton1ActionPerformed

    private void searchField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchField1ActionPerformed

    
    
 
private void setupFAQs() {
    // Ajustar tamaño de la ventana
    setSize(438, 533);
    setLocationRelativeTo(null);
    
    // Limpiar y configurar el panel principal
    jPanel1.removeAll();
    jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
    jPanel1.setBackground(new Color(178, 171, 171));
    
    // Configurar panel de navegación para que sea más compacto
    jPanel3.setPreferredSize(new Dimension(438, 35));
    jPanel3.setMaximumSize(new Dimension(438, 35));
    
    // Configurar título principal con tamaño más pequeño
    jLabel1.setText("Preguntas Frecuentes");
    jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 18)); // Reducido de 28 a 22
    jLabel1.setForeground(new Color(51, 102, 0));
    jLabel1.setAlignmentX(Component.CENTER_ALIGNMENT);
    
    // Panel para el título centrado más compacto
    JPanel titlePanel = new JPanel();
    titlePanel.setBackground(new Color(178, 171, 171));
    titlePanel.setMaximumSize(new Dimension(438, 38)); // Reducido de 50 a 40
    titlePanel.add(jLabel1);
    
    // Agregar componentes con menos espacio entre ellos
    jPanel1.add(jPanel3);
    jPanel1.add(Box.createRigidArea(new Dimension(0, 3))); // Reducido de 10 a 5
    jPanel1.add(titlePanel);
    jPanel1.add(Box.createRigidArea(new Dimension(0, 3))); // Reducido de 10 a 5
    
    // Crear panel contenedor para preguntas
    JPanel questionsContainer = new JPanel();
    questionsContainer.setLayout(new BoxLayout(questionsContainer, BoxLayout.Y_AXIS));
    questionsContainer.setBackground(new Color(178, 171, 171));
    
    // Panel para centrar las preguntas
    JPanel centeringPanel = new JPanel();
    centeringPanel.setLayout(new BoxLayout(centeringPanel, BoxLayout.Y_AXIS));
    centeringPanel.setBackground(new Color(178, 171, 171));
    centeringPanel.setAlignmentX(Component.CENTER_ALIGNMENT);
    
    // Agregar preguntas al contenedor
    addQuestionsToContainer(centeringPanel);
    
    // Panel con padding reducido
    JPanel paddingPanel = new JPanel();
    paddingPanel.setLayout(new BoxLayout(paddingPanel, BoxLayout.X_AXIS));
    paddingPanel.setBackground(new Color(178, 171, 171));
    paddingPanel.add(Box.createHorizontalStrut(8)); // Reducido de 20 a 10
    paddingPanel.add(centeringPanel);
    paddingPanel.add(Box.createHorizontalStrut(8)); // Reducido de 20 a 10
    
    questionsContainer.add(paddingPanel);
    
    // Configurar scroll pane
    JScrollPane scrollPane = new JScrollPane(questionsContainer);
    scrollPane.setBorder(null);
    scrollPane.setBackground(new Color(178, 171, 171));
    scrollPane.getViewport().setBackground(new Color(178, 171, 171));
    
    // Agregar scroll pane al panel principal
    jPanel1.add(scrollPane);
    
    // Configurar el campo de búsqueda
    setupSearchField();
}       

private JPanel createQuestionPanel(String question, String answer) {
    JPanel panel = new JPanel();
    panel.setLayout(new BorderLayout(3, 3)); // Reducido de 10,10 a 5,5
    panel.setBackground(new Color(240, 240, 240));
    panel.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(new Color(200, 200, 200), 1),
        BorderFactory.createEmptyBorder(6, 6, 6, 6) // Reducido de 15 a 
    ));
    panel.setMaximumSize(new Dimension(400, Integer.MAX_VALUE));
    
    // Panel para la pregunta con icono Q más compacto
    JPanel questionPanel = new JPanel(new BorderLayout(3, 0)); // Reducido de 10 a 5
    questionPanel.setOpaque(false);
    
    // Icono Q más pequeño
    JLabel iconLabel = new JLabel("Q");
    iconLabel.setFont(new Font("Segoe UI", Font.BOLD, 12)); // Reducido de 18 a 14
    iconLabel.setForeground(new Color(51, 102, 0));
    
    // Pregunta con fuente más pequeña
    JLabel questionLabel = new JLabel(question);
    questionLabel.setFont(new Font("Segoe UI", Font.BOLD, 10)); // Reducido de 14 a 12
    
    questionPanel.add(iconLabel, BorderLayout.WEST);
    questionPanel.add(questionLabel, BorderLayout.CENTER);
    
    // Respuesta con fuente más pequeña y ancho ajustado
    JLabel answerLabel = new JLabel(answer);
    answerLabel.setFont(new Font("Segoe UI", Font.PLAIN, 9)); // Reducido de 13 a 11
    
    panel.add(questionPanel, BorderLayout.NORTH);
    panel.add(answerLabel, BorderLayout.CENTER);
    
    return panel;
}

private void addQuestionsToContainer(JPanel container) {
    String[][] questions = {
        {"¿Qué es Black Box Security?",
         "<html><div style='width:300px;padding:3px'>" + // Reducido de 350 a 300
         "Black Box Security es un sistema integral diseñado para la gestión de " +
         "productos de seguridad, especializado en costeo rápido, control de " +
         "inventario y administración eficiente de usuarios." +
         "</div></html>"},
         
        {"¿Cómo realizar un costeo rápido?",
         "<html><div style='width:300px;padding:3px'>" +
         "1. Selecciona 'Costeo Rápido' en el menú principal<br>" +
         "2. Ingresa los datos del producto<br>" +
         "3. Completa los campos de costo FOB, flete y margen<br>" +
         "4. El sistema calculará automáticamente los costos" +
         "</div></html>"},
         
        {"¿Cómo gestionar usuarios?",
         "<html><div style='width:300px;padding:3px'>" +
         "Como administrador puedes:<br>" +
         "• Agregar nuevos usuarios<br>" +
         "• Editar perfiles existentes<br>" +
         "• Gestionar permisos y roles<br>" +
         "• Monitorear actividad del sistema" +
         "</div></html>"}
    };
    
    for (String[] question : questions) {
        JPanel panel = createQuestionPanel(question[0], question[1]);
        container.add(panel);
        container.add(Box.createRigidArea(new Dimension(0, 3))); // Reducido de 10 a 5
    }
}
private void searchQuestions(String searchText) {
    // Ignorar búsqueda si es el placeholder
    if (searchText.equals("Buscar pregunta...")) {
        return;
    }
    
    searchText = searchText.toLowerCase().trim();
    
    // Obtener el panel contenedor de preguntas (el que está dentro del JScrollPane)
    JScrollPane scrollPane = null;
    for (Component comp : jPanel1.getComponents()) {
        if (comp instanceof JScrollPane) {
            scrollPane = (JScrollPane) comp;
            break;
        }
    }
    
    if (scrollPane != null) {
        JViewport viewport = scrollPane.getViewport();
        JPanel questionsContainer = (JPanel) viewport.getView();
        
        Component[] components = questionsContainer.getComponents();
        
        // Iterar sobre cada panel de pregunta
        for (int i = 0; i < components.length; i++) {
            Component comp = components[i];
            if (comp instanceof JPanel) {
                JPanel questionPanel = (JPanel) comp;
                boolean found = false;
                
                // Buscar en el texto de la pregunta y respuesta
                for (Component c : questionPanel.getComponents()) {
                    if (c instanceof JPanel) {
                        // Panel de la pregunta
                        JPanel headerPanel = (JPanel) c;
                        for (Component headerComp : headerPanel.getComponents()) {
                            if (headerComp instanceof JLabel) {
                                JLabel label = (JLabel) headerComp;
                                if (label.getText().toLowerCase().contains(searchText)) {
                                    found = true;
                                    break;
                                }
                            }
                        }
                    } else if (c instanceof JLabel) {
                        // Panel de la respuesta
                        JLabel answerLabel = (JLabel) c;
                        String answerText = stripHTML(answerLabel.getText().toLowerCase());
                        if (answerText.contains(searchText)) {
                            found = true;
                            break;
                        }
                    }
                }
                
                // Mostrar u ocultar el panel según el resultado de la búsqueda
                questionPanel.setVisible(found || searchText.isEmpty());
                
                // Manejar el espacio rígido que sigue al panel (si existe)
                if (i + 1 < components.length && components[i + 1] instanceof Box.Filler) {
                    components[i + 1].setVisible(found || searchText.isEmpty());
                }
            }
        }
        
        // Refrescar el contenedor
        questionsContainer.revalidate();
        questionsContainer.repaint();
    }
}

// Método auxiliar para eliminar etiquetas HTML del texto
private String stripHTML(String html) {
    return html.replaceAll("\\<.*?\\>", "")
               .replaceAll("&nbsp;", " ")
               .replaceAll("&bull;", "•")
               .replaceAll("&middot;", "·")
               .trim();
}

// Agregar el listener para la búsqueda en tiempo real
private void setupSearchField() {
    searchField1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        public void changedUpdate(javax.swing.event.DocumentEvent e) { 
            handleSearch(); 
        }
        public void removeUpdate(javax.swing.event.DocumentEvent e) { 
            handleSearch(); 
        }
        public void insertUpdate(javax.swing.event.DocumentEvent e) { 
            handleSearch(); 
        }
    });
    
    // Placeholder para el campo de búsqueda
    searchField1.setForeground(Color.GRAY);
    searchField1.setText("Buscar pregunta...");
    
    searchField1.addFocusListener(new java.awt.event.FocusListener() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (searchField1.getText().equals("Buscar pregunta...")) {
                searchField1.setText("");
                searchField1.setForeground(Color.BLACK);
            }
        }
        
        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (searchField1.getText().isEmpty()) {
                searchField1.setForeground(Color.GRAY);
                searchField1.setText("Buscar pregunta...");
            }
        }
    });
}

private void handleSearch() {
    SwingUtilities.invokeLater(() -> {
        String searchText = searchField1.getText();
        searchQuestions(searchText);
    });
}

// Modificar el evento del botón de búsqueda

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreguntasFrecuentesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreguntasFrecuentesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreguntasFrecuentesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreguntasFrecuentesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreguntasFrecuentesForm("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookmarkButton1;
    private javax.swing.JButton flechaDerecha1;
    private javax.swing.JButton flechaIzquierda1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton menuButton1;
    private javax.swing.JButton recargar1;
    private java.awt.Scrollbar scrollbar1;
    private javax.swing.JButton searchButton1;
    private javax.swing.JTextField searchField1;
    // End of variables declaration//GEN-END:variables
}
